@startuml classdiagram

Actor Staff
rectangle YogiTrack {
    left to right direction
    Staff --> (Add a new Instructor)
    Staff --> (Add a new Class)
    Staff --> (Add a new Package)
    Staff --> (Add a new Customer)
    Staff --> (Record a Sale)
    Staff --> (Check-in a Customer)
}
@enduml 

